// Lógica e interações do teste vocacional.
let current=0,selected=null,scores=[];
const $=id=>document.getElementById(id);
function renderCourses(){ $('courseGrid').innerHTML=courses.map((c,i)=>`<article class="course" onclick="openCourse(${i})"><small>CAMINHO ${String(i+1).padStart(2,'0')}</small><h3>${c.name}</h3><p>${c.desc}</p><span class="course-link">Conhecer o curso →</span></article>`).join(''); }
function openCourse(i){const c=courses[i];$('modalTitle').textContent=c.name;$('modalDesc').textContent=c.desc;$('modalPpc').href=c.ppc;$('courseModal').classList.add('open');document.body.style.overflow='hidden'}
function closeModal(){$('courseModal').classList.remove('open');document.body.style.overflow=''}
function show(section){$('home').style.display=section==='home'?'block':'none';$('quiz').style.display=section==='quiz'?'block':'none';$('result').style.display=section==='result'?'block':'none'}
function goHome(){closeModal();show('home');history.replaceState(null,'','#');window.scrollTo(0,0)}
function startQuiz(){closeModal();current=0;selected=null;scores=Array(7).fill(0);show('quiz');history.replaceState(null,'','#quiz');renderQuestion();document.querySelector('.quiz-page').scrollIntoView({block:'start',behavior:'auto'})}
function renderQuestion(){const q=questions[current];$('counter').textContent=String(current+1).padStart(2,'0')+' / 15';$('qcat').textContent=q.cat;$('question').textContent=q.q;$('qnote').textContent=q.note;$('progress').style.width=((current+1)/questions.length*100)+'%';const box=$('answers');box.innerHTML='';selected=null;q.a.forEach((a,i)=>{const b=document.createElement('button');b.className='answer';b.innerHTML=`<span class="letter">${String.fromCharCode(65+i)}</span><span>${a[0]}</span>`;b.onclick=()=>selectAnswer(i,b);box.appendChild(b)});$('prev').disabled=current===0;$('next').disabled=true;$('next').textContent=current===questions.length-1?'Ver meu resultado →':'Continuar →'}
function selectAnswer(i,b){document.querySelectorAll('.answer').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=i;$('next').disabled=false}
function addScore(weights){Object.entries(weights).forEach(([i,v])=>scores[+i]+=v)}
function nextQuestion(){if(selected===null)return;addScore(questions[current].a[selected][1]);if(current<questions.length-1){current++;renderQuestion()}else showResult()}
function prevQuestion(){if(current===0)return;current--;renderQuestion()}
function showResult(){show('result');const ranked=scores.map((score,i)=>({score,i})).sort((a,b)=>b.score-a.score);const top=ranked[0];const total=scores.reduce((a,b)=>a+b,0)||1;const pct=Math.round(top.score/Math.max(...scores)*100);$('resultTitle').textContent=courses[top.i].name;$('resultText').textContent='Suas respostas indicam maior afinidade com uma trajetória que combina com a forma como você escolhe, analisa e transforma problemas. Isso não é uma sentença sobre seu futuro: é um ponto de partida para comparar cursos.';$('whyText').textContent=courses[top.i].why;$('matches').innerHTML=ranked.slice(0,3).map((r,n)=>`<article class="match ${n===0?'rank1':''}"><small>${n===0?'MAIOR AFINIDADE':n===1?'SEGUNDA AFINIDADE':'TERCEIRA AFINIDADE'}</small><h3>${courses[r.i].name}</h3><span class="pct">${Math.round(r.score/Math.max(...scores)*100)}% de compatibilidade relativa</span><div class="bar"><i style="width:${Math.max(10,r.score/Math.max(...scores)*100)}%"></i></div><button class="course-link" style="background:none;border:0;padding:0;cursor:pointer" onclick="openCourse(${r.i})">Conhecer este curso →</button></article>`).join('');history.replaceState(null,'','#resultado');document.querySelector('.result-page').scrollIntoView({block:'start',behavior:'auto'})}
document.addEventListener('keydown',e=>{if($('quiz').style.display==='block'){if(['1','2','3','4'].includes(e.key)){const i=+e.key-1;const b=document.querySelectorAll('.answer')[i];if(b)selectAnswer(i,b)}if(e.key==='Enter'&&!$('next').disabled)nextQuestion();if(e.key==='ArrowLeft')prevQuestion();if(e.key==='Escape')goHome()}});
renderCourses();
