// Dados dos cursos e perguntas do teste vocacional.
const courses=[
 {name:'Engenharia de Software',desc:'Desenvolvimento de software, sistemas, requisitos, arquitetura, qualidade e soluções digitais.',why:'Você tende a decompor problemas, organizar regras e pensar em soluções que precisam funcionar de forma consistente.',ppc:'https://ccnt.uepa.br/wp-content/uploads/2026/01/PPC-ENGENHARIA-DE-SOFTWARE.pdf'},
 {name:'Engenharia de Produção',desc:'Processos, operações, qualidade, logística, custos, dados e melhoria de sistemas produtivos.',why:'Você demonstra afinidade com organização, eficiência, análise de processos e decisões que equilibram recursos e resultados.',ppc:'https://ccnt.uepa.br/wp-content/uploads/2026/01/PPC-ENGENHARIA-DE-PRODUCAO.pdf'},
 {name:'Licenciatura em Física',desc:'Modelagem, matemática, experimentação, fenômenos físicos e formação para o ensino de Física.',why:'Você mostra interesse por entender relações entre variáveis, testar hipóteses e explicar fenômenos de maneira estruturada.',ppc:'https://paginas.uepa.br/fisica/wp-content/uploads/2022/05/Projeto-Pedagogico-Curso-Licenciatura-Fisica.pdf'},
 {name:'Licenciatura em Geografia',desc:'Espaço geográfico, território, sociedade, natureza, cartografia, análise espacial e ensino.',why:'Você tende a observar relações entre pessoas, lugares, território e transformações do espaço.',ppc:'https://prograd.uepa.br/cursos-do-ccse/'},
 {name:'Tecnologia em Alimentos',desc:'Matérias-primas, processos, qualidade, segurança, desenvolvimento e inovação em alimentos.',why:'Você demonstra curiosidade por transformações de materiais, controle de qualidade e aplicação prática da ciência.',ppc:'https://www.uepa.br/pt-br/content/centro-de-ciencias-naturais-e-tecnologia-ccnt'},
 {name:'Engenharia Ambiental e Sanitária',desc:'Água, resíduos, saneamento, prevenção de impactos, sistemas ambientais e saúde pública.',why:'Você tende a pensar em impactos, recursos, prevenção e soluções técnicas para problemas ambientais e sanitários.',ppc:'https://prograd.uepa.br/wp-content/uploads/2023/05/PPC-ENGENHARIA-AMBIENTAL-E-SANITARIA-Vol-1.pdf'},
 {name:'Engenharia Florestal',desc:'Manejo, conservação, recursos florestais, ecossistemas, tecnologia da madeira e produção sustentável.',why:'Você mostra afinidade com recursos naturais, sistemas florestais, conservação e uso planejado do território.',ppc:'https://ccnt.uepa.br/wp-content/uploads/2026/01/PPC-Engenharia-Florestal.pdf'}
];

// Cada alternativa distribui pontos por mais de um caminho para evitar respostas óbvias.
const questions=[
 {cat:'Problemas reais',note:'Pense no que você faria de verdade, não no que parece “mais certo”.',q:'Você recebe um problema que ninguém explicou direito. Qual é sua primeira reação?',a:[['Quebro o problema em partes menores e tento descobrir exatamente o que precisa acontecer.',{0:3,1:1}],['Organizo o que está acontecendo, os recursos envolvidos e onde parece estar o maior desperdício.',{1:3,0:1}],['Tento descobrir quais fatores podem explicar o comportamento e o que eu poderia medir.',{2:3,4:1}],['Procuro entender onde aquilo acontece, quem é afetado e o que muda de um lugar para outro.',{3:3,5:1}]]},
 {cat:'Quando algo dá errado',note:'Não existe uma resposta técnica “correta”; escolha a atitude que mais parece com você.',q:'Um projeto que estava funcionando começa a apresentar resultados diferentes. O que você faria?',a:[['Reproduziria o problema e verificaria quais condições fazem o erro aparecer.',{0:3,2:1}],['Compararia as etapas do processo para localizar onde a variação começou.',{1:3,4:1}],['Repetiria medições e testaria uma hipótese para descobrir qual variável mudou.',{2:3,5:1}],['Compararia os locais ou contextos em que o resultado mudou para procurar um padrão.',{3:3,6:1}]]},
 {cat:'Dados',note:'Imagine que você precisa tomar uma decisão com informação incompleta.',q:'Você tem muitos dados, mas não sabe ainda o que eles significam. Qual caminho parece mais natural?',a:[['Organizo os dados para conseguir consultar, filtrar e cruzar as informações.',{0:3,1:1}],['Transformo os dados em indicadores que ajudem a comparar desempenho e resultados.',{1:3,3:1}],['Procuro relações entre as variáveis e verifico se elas se repetem nas medições.',{2:3,4:1}],['Cruzo os dados com localização, contexto e características das áreas analisadas.',{3:3,5:1}]]},
 {cat:'Construindo uma solução',note:'Pense no processo desde a ideia até algo que realmente possa ser usado.',q:'Você precisa criar uma solução para facilitar uma tarefa repetitiva. O que mais combina com você?',a:[['Criar uma sequência de regras que execute a tarefa automaticamente e possa ser melhorada depois.',{0:3,2:1}],['Redesenhar o fluxo da tarefa para reduzir etapas, erros, tempo e desperdício.',{1:3,0:1}],['Testar diferentes formas de fazer a tarefa e medir qual produz o melhor resultado.',{2:3,4:1}],['Entender como a tarefa afeta pessoas, recursos e o ambiente antes de propor mudanças.',{5:3,3:1}]]},
 {cat:'Ciência na prática',note:'Escolha o tipo de investigação que mais combina com seu jeito.',q:'Você desconfia que uma mudança está alterando um resultado. Como gostaria de verificar?',a:[['Controlaria as condições, mudaria uma variável por vez e compararia os resultados.',{2:3,4:1}],['Montaria uma forma de registrar o processo e identificar em que etapa a mudança aparece.',{1:2,0:2}],['Observaria como o resultado se distribui em diferentes lugares ou grupos.',{3:3,6:1}],['Analisaria a composição, as propriedades e as condições do material envolvido.',{4:3,2:1}]]},
 {cat:'Ambiente e território',note:'Imagine que você precisa entender um problema que envolve espaço e recursos.',q:'Uma área está sofrendo mudanças rápidas. O que você gostaria de investigar primeiro?',a:[['Como as atividades humanas estão distribuídas e como elas transformam o espaço.',{3:3,5:1}],['Quais recursos naturais estão envolvidos e como seu uso pode ser planejado.',{6:3,5:1}],['Quais impactos estão sendo gerados e como poderiam ser prevenidos ou reduzidos.',{5:3,3:1}],['Quais dados e indicadores poderiam acompanhar a mudança ao longo do tempo.',{1:2,2:2}]]},
 {cat:'Tecnologia',note:'Você não precisa ser programador para responder esta questão.',q:'Um sensor começa a enviar informações para um sistema. O que mais desperta sua curiosidade?',a:[['Como transformar a leitura em regras para o sistema tomar uma decisão.',{0:3,2:1}],['Como usar os dados para acompanhar desempenho e melhorar o processo.',{1:3,0:1}],['Como a grandeza medida se relaciona com o fenômeno observado.',{2:3,4:1}],['Como representar as medições e comparar o comportamento em diferentes pontos.',{3:3,5:1}]]},
 {cat:'Organização',note:'Escolha a forma de trabalho que você realmente teria vontade de assumir.',q:'Um grupo precisa entregar um projeto com prazo curto e muitos recursos envolvidos. Qual papel você assumiria?',a:[['Definir requisitos, dividir o problema e acompanhar se cada parte funciona.',{0:3,1:1}],['Organizar cronograma, recursos, prioridades e indicadores de acompanhamento.',{1:3,3:1}],['Definir como testar a solução e quais evidências seriam necessárias para validá-la.',{2:3,4:1}],['Entender as condições do local e os impactos que o projeto pode causar.',{5:2,3:2}]]},
 {cat:'Materiais e processos',note:'Pense em algo que precisa sair de uma condição e chegar a outra com controle.',q:'Um material passa por várias etapas até virar um produto. O que mais chama sua atenção?',a:[['As propriedades do material e o que muda durante as transformações.',{4:3,2:1}],['Como controlar as etapas para manter o resultado dentro do padrão.',{1:2,4:2}],['Como automatizar medições e ações para reduzir falhas no processo.',{0:2,1:2}],['Como o processo consome recursos e quais resíduos ou impactos ele gera.',{5:3,6:1}]]},
 {cat:'Explicar e ensinar',note:'A pergunta não mede “ser professor”; mede como você transforma conhecimento em algo compreensível.',q:'Alguém não entendeu uma ideia que para você parece simples. O que você faria?',a:[['Criaria uma sequência de exemplos e regras até a pessoa conseguir aplicar sozinha.',{0:2,2:2}],['Organizaria a explicação em etapas e relacionaria cada parte ao resultado final.',{1:2,3:2}],['Usaria uma demonstração, experimento ou representação para tornar o fenômeno observável.',{2:3,4:1}],['Partiria de uma situação do cotidiano e relacionaria o conteúdo ao lugar e à realidade da pessoa.',{3:3,5:1}]]},
 {cat:'Decisões',note:'Imagine que duas soluções funcionam, mas uma delas exige mais recursos.',q:'Como você escolheria entre as duas?',a:[['Compararia requisitos, limitações e possibilidade de manutenção ao longo do tempo.',{0:3,1:1}],['Compararia custo, tempo, produtividade, riscos e impacto no processo.',{1:3,5:1}],['Compararia os resultados dos testes e a consistência das medições.',{2:3,4:1}],['Consideraria efeitos sobre pessoas, território, recursos naturais e contexto.',{3:2,5:2}]]},
 {cat:'Natureza e recursos',note:'Não escolha pela área “bonita”; escolha pelo tipo de trabalho que você faria.',q:'Você recebe uma área para estudar e precisa propor um uso responsável. O que faria?',a:[['Mapearia características, cobertura, distribuição e relações entre os elementos da área.',{3:3,6:1}],['Avaliaría ecossistemas, regeneração, manejo e possibilidade de uso sustentável.',{6:3,5:1}],['Estudaria água, solo, resíduos e possíveis impactos das atividades planejadas.',{5:3,6:1}],['Definiria indicadores para acompanhar produtividade e eficiência do uso dos recursos.',{1:3,3:1}]]},
 {cat:'Qualidade',note:'Pense em um produto ou serviço que precisa manter o mesmo padrão.',q:'Um lote apresentou resultado diferente dos anteriores. Qual investigação você faria?',a:[['Verificaria composição, processamento, armazenamento e parâmetros de qualidade.',{4:3,1:1}],['Rastrearia as etapas e os registros do processo para descobrir onde ocorreu a mudança.',{1:3,0:1}],['Repetiria medições e testaria hipóteses sobre as variáveis que podem ter causado a diferença.',{2:3,4:1}],['Compararia condições de transporte, ambiente e localização das ocorrências.',{5:2,3:2}]]},
 {cat:'Visão de futuro',note:'Escolha o tipo de projeto que você teria mais vontade de acompanhar por meses.',q:'Qual projeto parece mais interessante para você?',a:[['Construir uma ferramenta digital que resolva um problema real e possa evoluir com o tempo.',{0:3,1:1}],['Redesenhar uma operação para aumentar eficiência, qualidade e aproveitamento de recursos.',{1:3,5:1}],['Investigar um fenômeno, testar modelos e explicar por que os resultados acontecem.',{2:3,4:1}],['Planejar uma intervenção considerando território, natureza, recursos e impactos de longo prazo.',{3:2,5:2,6:1}]]},
 {cat:'Seu jeito de resolver',note:'Última pergunta: escolha sem pensar no nome dos cursos.',q:'Quando você encontra um problema que realmente te interessa, o que costuma acontecer?',a:[['Quero entender a lógica por trás dele e imaginar como construir uma solução.',{0:3,2:1}],['Começo a organizar as partes, comparar alternativas e pensar em como melhorar o resultado.',{1:3,4:1}],['Quero investigar, testar, medir e descobrir o que explica aquilo.',{2:3,4:1}],['Quero entender o contexto, as relações e os efeitos que aquilo provoca no espaço ou no ambiente.',{3:2,5:2,6:1}]]}
];
